export interface EnglishEpisodeInfo {
  fileName: string;
  titleEn: string;
}

export const ENGLISH_NOVEL_MAP: Record<number, EnglishEpisodeInfo> = {
  1: { fileName: "SNSHero_Novel_Episode_01_Two_Vows_Beneath_the_Blizzard_EN.txt", titleEn: "Two Vows Beneath the Blizzard" },
  2: { fileName: "SNSHero_Novel_Episode_02_Oath_of_the_Seven_Pursuers_EN.txt", titleEn: "Oath of the Seven Pursuers" },
  3: { fileName: "SNSHero_Novel_Episode_03_Blood_on_the_Mist_Cliff_EN.txt", titleEn: "Blood on the Mist Cliff" },
  4: { fileName: "SNSHero_Novel_Episode_04_The_Child_Raised_in_the_Wastes_EN.txt", titleEn: "The Child Raised in the Wastes" },
  5: { fileName: "SNSHero_Novel_Episode_05_Phantom_in_the_Downpour_EN.txt", titleEn: "Phantom in the Downpour" },
  6: { fileName: "SNSHero_Novel_Episode_06_The_Art_of_Breathing_Stars_EN.txt", titleEn: "The Art of Breathing Stars" },
  7: { fileName: "SNSHero_Novel_Episode_07_The_Traitors_Camp_EN.txt", titleEn: "The Traitors Camp" },
  8: { fileName: "SNSHero_Novel_Episode_08_Rider_of_the_Crimson_Mane_EN.txt", titleEn: "Rider of the Crimson Mane" },
  9: { fileName: "SNSHero_Novel_Episode_09_Wind_in_Beggars_Clothes_EN.txt", titleEn: "Wind in Beggars Clothes" },
  10: { fileName: "SNSHero_Novel_Episode_10_Prisoner_of_the_Flame_Court_EN.txt", titleEn: "Prisoner of the Flame Court" },
  11: { fileName: "SNSHero_Novel_Episode_11_The_Dagger_That_Wakes_Memory_EN.txt", titleEn: "The Dagger That Wakes Memory" },
  12: { fileName: "SNSHero_Novel_Episode_12_Spring_Between_Two_Graves_EN.txt", titleEn: "Spring Between Two Graves" },
  13: { fileName: "SNSHero_Novel_Episode_13_Master_of_the_Jade_Staff_EN.txt", titleEn: "Master of the Jade Staff" },
  14: { fileName: "SNSHero_Novel_Episode_14_Guests_of_the_Mist_Lake_EN.txt", titleEn: "Guests of the Mist Lake" },
  15: { fileName: "SNSHero_Novel_Episode_15_Night_of_Serpent_and_Lion_EN.txt", titleEn: "Night of Serpent and Lion" },
  16: { fileName: "SNSHero_Novel_Episode_16_Brothers_Before_the_Ruins_EN.txt", titleEn: "Brothers Before the Ruins" },
  17: { fileName: "SNSHero_Novel_Episode_17_Invitation_to_the_Wind_Isle_EN.txt", titleEn: "Invitation to the Wind Isle" },
  18: { fileName: "SNSHero_Novel_Episode_18_Secret_of_the_Black_Sanctum_EN.txt", titleEn: "Secret of the Black Sanctum" },
  19: { fileName: "SNSHero_Novel_Episode_19_Three_Trials_EN.txt", titleEn: "Three Trials" },
  20: { fileName: "SNSHero_Novel_Episode_20_The_Wave_That_Swallowed_the_Flower_Ship_EN.txt", titleEn: "The Wave That Swallowed the Flower Ship" },
  21: { fileName: "SNSHero_Novel_Episode_21_Betrayal_Aboard_the_Burning_Ship_EN.txt", titleEn: "Betrayal Aboard the Burning Ship" },
  22: { fileName: "SNSHero_Novel_Episode_22_Four_on_a_Deserted_Island_EN.txt", titleEn: "Four on a Deserted Island" },
  23: { fileName: "SNSHero_Novel_Episode_23_The_Record_Sleeping_in_the_Cave_EN.txt", titleEn: "The Record Sleeping in the Cave" },
  24: { fileName: "SNSHero_Novel_Episode_24_Seven_Nights_in_the_Sealed_Chamber_EN.txt", titleEn: "Seven Nights in the Sealed Chamber" },
  25: { fileName: "SNSHero_Novel_Episode_25_Night_of_the_False_Wedding_EN.txt", titleEn: "Night of the False Wedding" },
  26: { fileName: "SNSHero_Novel_Episode_26_Open_Door_Closed_Heart_EN.txt", titleEn: "Open Door, Closed Heart" },
  27: { fileName: "SNSHero_Novel_Episode_27_Between_Two_Promises_EN.txt", titleEn: "Between Two Promises" },
  28: { fileName: "SNSHero_Novel_Episode_28_Revolt_of_the_Jade_Council_EN.txt", titleEn: "Revolt of the Jade Council" },
  29: { fileName: "SNSHero_Novel_Episode_29_Queen_of_the_Wind_EN.txt", titleEn: "Queen of the Wind" },
  30: { fileName: "SNSHero_Novel_Episode_30_Poison_at_the_Four_Gates_EN.txt", titleEn: "Poison at the Four Gates" },
  31: { fileName: "SNSHero_Novel_Episode_31_The_Hand_That_Wagered_Everything_EN.txt", titleEn: "The Hand That Wagered Everything" },
  32: { fileName: "SNSHero_Novel_Episode_32_Echo_of_First_Love_EN.txt", titleEn: "Echo of First Love" },
  33: { fileName: "SNSHero_Novel_Episode_33_Grudge_of_the_Black_Marsh_EN.txt", titleEn: "Grudge of the Black Marsh" },
  34: { fileName: "SNSHero_Novel_Episode_34_The_Fallen_Wind_Isle_EN.txt", titleEn: "The Fallen Wind Isle" },
  35: { fileName: "SNSHero_Novel_Episode_35_Mistaken_in_the_Fog_EN.txt", titleEn: "Mistaken in the Fog" },
  36: { fileName: "SNSHero_Novel_Episode_36_Map_of_the_Cross_Shaped_Scar_EN.txt", titleEn: "Map of the Cross-Shaped Scar" },
  37: { fileName: "SNSHero_Novel_Episode_37_War_of_the_Conqueror_King_EN.txt", titleEn: "War of the Conqueror King" },
  38: { fileName: "SNSHero_Novel_Episode_38_Three_Silk_Seals_EN.txt", titleEn: "Three Silk Seals" },
  39: { fileName: "SNSHero_Novel_Episode_39_The_World_Worth_Protecting_EN.txt", titleEn: "The World Worth Protecting" },
  40: { fileName: "SNSHero_Novel_Episode_40_One_Who_Is_Not_Called_a_Hero_EN.txt", titleEn: "One Who Is Not Called a Hero" },
};
